DATASET=('fmnist',)
TGT_EPOCHS=(0,)
PCT=(20,)
EPS=(1.0,)
TARGETED=(True,)
ATK = ('inf',)
NOTE=('earlyStop',)

# DATASET=('fmnist',)
# TGT_EPOCHS=(0,)
# PCT=(20,)
# EPS=(0.0,)
# TARGETED=(True,)
# ATK = ('inf',)
# NOTE=('downgrade',)
